### ISSUE TITLE
你好 我发现一个bug 就是在组件里面引入remoteJS的时候会出现问题

### ISSUE THREAD

**Issue by yehoan** [qinmao/vue-remote-js#1]
![image](https://user-images.githubusercontent.com/22631753/41959142-b8d22a9a-7a1e-11e8-9a54-9402df3ee5b6.png)
![image](https://user-images.githubusercontent.com/22631753/41959166-cb091e26-7a1e-11e8-8279-0c05a608a0d2.png)

**Comment by qinmao** [comment]
当时开发这款插件的时候，是把它当做一个全局的通用组件来做的，你要在main.js 中
![image](https://user-images.githubusercontent.com/26270074/42863653-61fc830e-8a96-11e8-89d0-b790b448dc70.png) 全局注册。在每个页面就不用在import引了直接用就可以了。是你使用的问题，当然了，如果你只要作为一个局部的组件来用，也可以，直接把源码稍微改下就ok了。
